name: aps_aide
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:

  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_lints: ^3.0.0
  flutter_screenutil: ^5.9.0
  crypto: ^3.0.3
  cookie_jar: ^4.0.8
  dio: ^5.4.3+1
  dio_cookie_manager: ^3.1.1
  flutter_easyloading: ^3.0.5
  get_storage: ^2.1.1
  fluttertoast: ^8.2.2
  intl: ^0.19.0
  pinput: ^3.0.0



  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-Semibold
      fonts:
        - asset: assets/fonts/Poppins-Semibold.ttf

