///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppImages {
  AppImages._();

  static const String icAppLogo = 'assets/images/ic_app_logo.png';
  static const String icAuthBg = 'assets/images/ic_auth_bg.png';
  static const String icBack = 'assets/images/ic_back.png';
  static const String icEmail = 'assets/images/ic_email.png';
  static const String icEye = 'assets/images/ic_eye.png';
  static const String icEyeClosed = 'assets/images/ic_eye_closed.png';
  static const String icLock = 'assets/images/ic_lock.png';
  static const String icLoginBgMob = 'assets/images/ic_login_bg_mob.png';
  static const String icLoginBgWeb = 'assets/images/ic_login_bg_web.png';
  static const String icTopLogoDesign = 'assets/images/ic_top_logo_design.png';
  static const String icTopLogoDesign2 = 'assets/images/ic_top_logo_design2.png';
  static const String poppinsBold = 'assets/fonts/Poppins-Bold.ttf';
  static const String poppinsLight = 'assets/fonts/Poppins-Light.ttf';
  static const String poppinsMedium = 'assets/fonts/Poppins-Medium.ttf';
  static const String poppinsRegular = 'assets/fonts/Poppins-Regular.ttf';
  static const String poppinsSemiBold = 'assets/fonts/Poppins-SemiBold.ttf';
}
